<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [7]:
import os

In [8]:
datos = os.listdir()
datos

['.git',
 'laboratorio-modulo1-leccion01-break-pass-continue.ipynb',
 'laboratorio-modulo1-leccion01-manejo-errores.ipynb',
 'laboratorio-modulo1-leccion02-clases.ipynb',
 'laboratorio-modulo2-leccion01-numpy.ipynb',
 'README.md']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


In [12]:
import numpy as np

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [13]:
lista = list(range(0,10))
array_1D = np.array(lista)
print(array_1D)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [14]:
array_2D = np.reshape(array_1D,(2,5))
print(array_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [61]:
array_ej3=np.array([0,2,0,3,0,4,0])

In [63]:
array_ej3_filtrado = np.where(array_ej3 != 0)
array_ej3_filtrado

(array([1, 3, 5]),)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [15]:
array_aleatorio_33 = np.random.rand(3,3)
print(array_aleatorio_33)

[[0.72131209 0.53761927 0.48495459]
 [0.29374852 0.21431286 0.34885266]
 [0.2283041  0.42018617 0.92688583]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [16]:
array_aleatorio_10 = np.random.randint(-3,67,(2,5))
print(array_aleatorio_10)
minimo = np.min(array_aleatorio_10)
maximo = np.max(array_aleatorio_10)
print(f"El número mínimo es {minimo}")
print(f"El número máximo es {maximo}")

[[36 55 65 56 10]
 [37 -3  1 56 62]]
El número mínimo es -3
El número máximo es 65


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
array_1D_2 = np.array([1,2,3,4,5,6,7,8])

In [50]:
array_1D_2_invertido = array_1D_2[::-1]
array_1D_2_invertido

array([8, 7, 6, 5, 4, 3, 2, 1])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [18]:
array_24 = np.arange(1,25)
array_3D = np.reshape(array_24,(2,3,4))
print(array_3D)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [64]:
array_3D[1,0,2]

np.int64(15)

In [19]:
primer_array = array_3D[0,:,:]
print(primer_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
ultima_fila = array_3D[1,2,:]
print(ultima_fila)

[21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [21]:
array_30 = np.arange(1,31)
array_3D_2 = np.reshape(array_30,(3,2,5))
print(array_3D_2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [22]:
dos_primeros = array_3D_2[0,:,0:2]
dos_primeros

array([[1, 2],
       [6, 7]])

In [23]:
dos_ultimos = array_3D_2[1:,:,:]
dos_ultimos

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [72]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_3D_3 = np.reshape(array_24, (4,3,2))
print(array_3D_3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]


In [75]:
array_3D_3[1,1,:]=[0,0]
array_3D_3[3,:,:]=[[-1,-1],[-1,-1],[-1,-1]]
array_3D_3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 0,  0],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]])


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [25]:
array_1013 = np.arange(-10,14)
array_3D_4 = np.reshape(array_1013,(2,4,3))
print(array_3D_4)

[[[-10  -9  -8]
  [ -7  -6  -5]
  [ -4  -3  -2]
  [ -1   0   1]]

 [[  2   3   4]
  [  5   6   7]
  [  8   9  10]
  [ 11  12  13]]]


In [79]:
array_3D_4_filtrado = array_3D_4[array_3D_4 >5]
array_3D_4_filtrado

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [83]:
array_3D_4_filtrado2 = np.where(array_3D_4 < 0,0,array_3D_4)
array_3D_4_filtrado2

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  1]],

       [[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]]])

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [102]:
array_27 = np.arange(1,28)
array_3D_5 = np.reshape(array_27,(3,3,3))
print(array_3D_5)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [103]:
subarray=array_3D_5[1,:,0:2]
subarray

array([[10, 11],
       [13, 14],
       [16, 17]])

In [107]:
subarray2=array_3D_5[array_3D_5>20]
subarray2

array([21, 22, 23, 24, 25, 26, 27])

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [28]:
array_ej11a = np.random.randint(0, 67, (1,10))
print(array_ej11a)

[[23 21 51 20 13 48 11 28 41 22]]


In [97]:
max_ej11=np.max(array_ej11a)
min_ej11=np.min(array_ej11a)

In [115]:
array_ej11a_2 = np.where((array_ej11a == max_ej11) | (array_ej11a == min_ej11),0,array_ej11a)
print(array_ej11a_2)


[[23 21  0 20 13 48  0 28 41 22]]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [29]:
array_ej12a = np.random.randint(0, 101, (1,15))
print(array_ej12a)

[[75 63 32 23 26  3 83 55 52 43 87 65 35 53 81]]


In [30]:
array_ordenado = np.sort(array_ej12a)
print(array_ordenado)

[[ 3 23 26 32 35 43 52 53 55 63 65 75 81 83 87]]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [31]:
array_ej11b = np.random.randint(-16,15,(4,4))
print(array_ej11b)

[[-13   8  14  -9]
 [-15   6   9 -11]
 [  7  12  14  -3]
 [  6  -6   0   9]]


In [32]:
suma_columnas = np.sum(array_ej11b, axis=0)
suma_filas = np.sum(array_ej11b, axis=1)
print(f"La suma a lo largo de las filas de la matriz es {suma_filas} y a lo largo de las columnas es {suma_columnas}")

La suma a lo largo de las filas de la matriz es [  0 -11  30   9] y a lo largo de las columnas es [-15  20  37 -14]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [33]:
lista_array55 = [[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]]
array_ej12b = np.array(lista_array55)
print(array_ej12b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [34]:
array_ej13 = np.random.randint(0,10,(2,5))
print(array_ej13)

[[5 4 0 7 4]
 [0 6 3 1 0]]


In [35]:
media = np.mean(array_ej13)
desviacion_estandar = np.std(array_ej13)
print(f"La media del array es {media} y la desviacion estándar es {desviacion_estandar}")

La media del array es 3.0 y la desviacion estándar es 2.4899799195977463


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [36]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_ej14 = np.reshape(array_24,(2,3,4))
print(array_ej14)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [43]:
array_ej14_transpuesto = np.transpose(array_ej14,(2,1,0))
array_ej14_transpuesto

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

Se han intercambiado matrices y columnas, antes había 2 matrices de 4 columnas y ahora hay 4 matrices de 2 columnas cada una. El número de filas se mantiene en 3.
Los cambios de índice lo muestran, el que en el array original indica la matriz, pasa a indicar las columnas en elarray nuevo:
Número | Índice anterior | Índice nuevo
------ | --------------- | ------------
1      | [0,0,0]         | [0,0,0]     
2      | [0,0,1]         | [1,0,0]     
3      | [0,0,2]         | [2,0,0]     
4      | [0,0,3]         | [3,0,0]     
5      | [0,1,0]         | [0,1,0]     
6      | [0,1,1]         | [1,1,0]     
7      | [0,1,2]         | [2,0,1]     
8      | [0,1,3]         | [3,1,0]     
9      | [0,2,0]         | [0,2,0]     
10     | [0,1,1]         | [1,1,0]     
11     | [0,2,2]         | [2,2,0]     
12     | [0,2,3]         | [3,2,0]     
13     | [1,0,0]         | [0,0,1]     
14     | [1,0,1]         | [1,0,1]     
15     | [1,0,2]         | [2,0,1]     
16     | [1,0,3]         | [3,0,1]     
17     | [1,1,0]         | [0,1,1]     
18     | [1,1,1]         | [1,1,1]     
19     | [1,1,2]         | [2,1,1]     
20     | [1,1,3]         | [3,1,1]     
21     | [1,2,0]         | [0,2,1]     
22     | [1,2,1]         | [1,2,1]     
23     | [1,2,2]         | [2,2,1]     
24     | [1,2,3]         | [3,2,1]     

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [40]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_ej15 = np.reshape(array_24,(3,4,2))
print(array_ej15)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


In [45]:
array_ej15_transpuesto = np.transpose(array_ej15,(1,0,2))
array_ej15_transpuesto

array([[[ 1,  2],
        [ 9, 10],
        [17, 18]],

       [[ 3,  4],
        [11, 12],
        [19, 20]],

       [[ 5,  6],
        [13, 14],
        [21, 22]],

       [[ 7,  8],
        [15, 16],
        [23, 24]]])

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [41]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_ej16 = np.reshape(array_24,(3,2,4))
print(array_ej16)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [46]:
array_ej16_transpuesto = np.transpose(array_ej16, (2,0,1))
array_ej16_transpuesto

array([[[ 1,  5],
        [ 9, 13],
        [17, 21]],

       [[ 2,  6],
        [10, 14],
        [18, 22]],

       [[ 3,  7],
        [11, 15],
        [19, 23]],

       [[ 4,  8],
        [12, 16],
        [20, 24]]])

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [55]:
array_ej17 = np.random.randint(-10,11,(3,4,5))
print(array_ej17)

[[[-10   4 -10   2 -10]
  [ -1  -2   9 -10   0]
  [ 10   5  -2  10  -2]
  [  2  -2  -8  -2  -2]]

 [[  5   6  -6   4  -5]
  [  1   9   5   0  -9]
  [ -1   1   0 -10  10]
  [ 10  -8   5  -4  -8]]

 [[  0   0 -10   4   0]
  [  8  -6  -8  -1  10]
  [ -2  -9  10   5  10]
  [ -4  -5  -9  -9 -10]]]


In [60]:
mediana = np.median(array_ej17)
print(mediana)
maximo = np.max(array_ej17)
print(maximo)
minimo = np.min(array_ej17)
print(minimo)

-1.0
10
-10


In [56]:
array_vacio = np.empty((3,4,5), dtype=int)
array_vacio

array([[[              0,               0,               0,
         140724231471648,              55],
        [  2021118405488,   2021118406640,   2021118409712,
           2021118404976,   2021118407344],
        [  2021118407408,   2021118406320,   2021118406704,
           2021118405040,   2021118391088],
        [  2021118405552,   2021118406768,   2021118407856,
           2021118407984,   2021118407472]],

       [[  2021118407536,   2021118408048,   2021118405104,
           2021118405616,   2021118405680],
        [  2021118408112,   2021118405744,   2021118407600,
           2021118408176,   2021118390992],
        [  2021118406384,   2021118371808,   2021118407664,
           2021118407728,   2021118408304],
        [  2021118405808,   2021118406832,   2021118405872,
           2021118406896,   2021118405936]],

       [[  2021118406000,   2021118406064,   2021118406960,
           2021118406128,   2021118405168],
        [  2021118408752,   2021118407792,   2021118406192,


In [116]:
array_vacio = np.where(array_ej17 == mediana, "M", array_vacio)
array_vacio = np.where(array_ej17 > mediana, "X", array_vacio)
array_vacio = np.where(array_ej17 < mediana, "Y", array_vacio)
array_vacio = np.where(array_ej17 == maximo, "MAX", array_vacio)
array_vacio = np.where(array_ej17 == minimo, "MIN", array_vacio)
print(array_vacio)

[[['MIN' 'X' 'MIN' 'X' 'MIN']
  ['M' 'Y' 'X' 'MIN' 'X']
  ['MAX' 'X' 'Y' 'MAX' 'Y']
  ['X' 'Y' 'Y' 'Y' 'Y']]

 [['X' 'X' 'Y' 'X' 'Y']
  ['X' 'X' 'X' 'X' 'Y']
  ['M' 'X' 'X' 'MIN' 'MAX']
  ['MAX' 'Y' 'X' 'Y' 'Y']]

 [['X' 'X' 'MIN' 'X' 'X']
  ['X' 'Y' 'Y' 'M' 'MAX']
  ['Y' 'Y' 'MAX' 'X' 'MAX']
  ['Y' 'Y' 'Y' 'Y' 'MIN']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [129]:
array_ej18 = np.random.randint(0,16,(4,4))
print(array_ej18)

[[ 3  6 13  2]
 [15  2 13  4]
 [ 4  4  1  1]
 [15  6  5  6]]
