<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [2]:
import os

In [4]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo2-leccion05-limpieza.ipynb',
 'laboratorio-modulo2-leccion04-visualizacion.ipynb',
 'laboratorio-modulo2-leccion03-groupby.ipynb',
 'laboratorio-modulo2-leccion02-eda-union.ipynb',
 'laboratorio-modulo2-leccion03-filtrado.ipynb']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


In [1]:
import numpy as np

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [6]:
lista = list(range(0,10))
array_1D = np.array(lista)
print(array_1D)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [9]:
array_2D = np.reshape(array_1D,(2,5))
print(array_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [20]:
array_aleatorio_33 = np.random.rand(3,3)
print(array_aleatorio_33)

[[0.03854704 0.7901486  0.53485893]
 [0.30866955 0.71724742 0.16702223]
 [0.64747573 0.71158025 0.38650356]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [24]:
array_aleatorio_10 = np.random.randint(-3,67,(2,5))
print(array_aleatorio_10)
minimo = np.min(array_aleatorio_10)
maximo = np.max(array_aleatorio_10)
print(f"El número mínimo es {minimo}")
print(f"El número máximo es {maximo}")

[[41 53 53 61 40]
 [ 2 36 31 16  9]]
El número mínimo es 2
El número máximo es 61


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
array_1D_2 = np.array([1,2,3,4,5,6,7,8])



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [31]:
array_24 = np.arange(1,25)
array_3D = np.reshape(array_24,(2,3,4))
print(array_3D)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [54]:
primer_array = array_3D[0,:,:]
print(primer_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
ultima_fila = array_3D[1,2,:]
print(ultima_fila)

[21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [32]:
array_30 = np.arange(1,31)
array_3D_2 = np.reshape(array_30,(3,2,5))
print(array_3D_2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [58]:
dos_primeros = array_3D_2[0,:,0:2]
dos_primeros

array([[1, 2],
       [6, 7]])

In [59]:
dos_ultimos = array_3D_2[1:,:,:]
dos_ultimos

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [ ]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_3D_3 = np.reshape(array_24, (4,3,2))
print(array_3D_3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [35]:
array_1013 = np.arange(-10,14)
array_3D_4 = np.reshape(array_1013,(2,4,3))
print(array_3D_4)

[[[-10  -9  -8]
  [ -7  -6  -5]
  [ -4  -3  -2]
  [ -1   0   1]]

 [[  2   3   4]
  [  5   6   7]
  [  8   9  10]
  [ 11  12  13]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [36]:
array_27 = np.arange(1,28)
array_3D_5 = np.reshape(array_27,(3,3,3))
print(array_3D_5)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [61]:
subarray=array_3D_5[1,:,0:2]
subarray

array([[10, 11],
       [13, 14],
       [16, 17]])

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [53]:
array_ej11a = np.random.randint(0, 67, (1,10))
print(array_ej11a)

[[61 42 28 25 39 66 20 13 47 60]]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [69]:
array_ej12a = np.random.randint(0, 101, (1,15))
print(array_ej12a)

[[30 54 58 73 72 45 94 89 64 28  3 72 14 92 66]]


In [70]:
array_ordenado = np.sort(array_ej12a)
print(array_ordenado)

[[ 3 14 28 30 45 54 58 64 66 72 72 73 89 92 94]]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [64]:
array_ej11b = np.random.randint(-16,15,(4,4))
print(array_ej11b)

[[  8  12  13   5]
 [-16   6 -15   7]
 [ 13  -4   9   1]
 [ -6 -11  13   4]]


In [67]:
suma_columnas = np.sum(array_ej11b, axis=0)
suma_filas = np.sum(array_ej11b, axis=1)
print(f"La suma a lo largo de las filas de la matriz es {suma_filas} y a lo largo de las columnas es {suma_columnas}")

La suma a lo largo de las filas de la matriz es [ 38 -18  19   0] y a lo largo de las columnas es [-1  3 20 17]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [72]:
lista_array55 = [[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]]
array_ej12b = np.array(lista_array55)
print(array_ej12b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [47]:
array_ej13 = np.random.randint(0,10,(2,5))
print(array_ej13)

[[2 2 8 6 9]
 [5 6 0 6 2]]


In [65]:
media = np.mean(array_ej13)
desviacion_estandar = np.std(array_ej13)
print(f"La media del array es {media} y la desviacion estándar es {desviacion_estandar}")

La media del array es 4.6 y la desviacion estándar es 2.8000000000000003


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [37]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_ej14 = np.reshape(array_24,(2,3,4))
print(array_ej14)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
array_transpuesto = np.transpose

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [38]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_ej15 = np.reshape(array_24,(3,4,2))
print(array_ej15)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [39]:
## se reutiliza el array unidimensional con valores enteros del 1 al 24 creado en el ejercio 6 "array_24"
array_ej16 = np.reshape(array_24,(3,2,4))
print(array_ej16)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [42]:
array_ej17 = np.random.randint(-10,11,(3,4,5))
print(array_ej17)

[[[  0   2  -4   4  -7]
  [ -1  -1 -10  -2   7]
  [-10  -4  -4  -4  -5]
  [  4  -8  -7   8  -2]]

 [[  2  -7  -7   9   2]
  [ -7   7  -2   9   2]
  [-10   3   0   5  -1]
  [ -1   8 -10  -5   0]]

 [[ -7  10  -7 -10   2]
  [ 10   4  -3  -1  -3]
  [ -8   5  -8   5  -8]
  [ -8   6  -4   3  -4]]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [41]:
array_ej18 = np.random.randint(0,16,(4,4))
print(array_ej18)

[[ 4  2 13  0]
 [12  7 10  3]
 [12  3  6 14]
 [13 10 12  7]]
